# Generated by Django 2.2.3 on 2019-07-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20190717_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female')], max_length=10, null=True),
        ),
    ]
