# Generated by Django 2.2.4 on 2019-08-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='email', max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='firstname',
            field=models.CharField(default='firstname', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lastname',
            field=models.CharField(default='lastname', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(default='location', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='national_id',
            field=models.CharField(default='national id', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nationality',
            field=models.CharField(default='nationality', max_length=40),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='phone number', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female')], default='sex', max_length=10),
        ),
    ]
