# Generated by Django 2.2.3 on 2019-07-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20190717_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='disabilities',
            field=models.ManyToManyField(blank=True, to='user_profile.Disability'),
        ),
    ]
