# Generated by Django 2.2.4 on 2019-08-09 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20190808_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdisability',
            name='disability',
        ),
        migrations.RemoveField(
            model_name='userdisability',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='disabilities',
        ),
        migrations.AddField(
            model_name='profile',
            name='cause',
            field=models.CharField(choices=[('ILLNESS', 'illness'), ('BIRTH', 'birth'), ('ACCIDENT', 'accident')], default='BIRTH', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='disability',
            field=models.CharField(choices=[('ALBINISM', 'albinism'), ('PHYSICAL', 'physical'), ('MENATL', 'mental'), ('VISUAL', 'visual'), ('HEARING', 'hearing'), ('EPILEPSY', 'epilepsy'), ('BLIND', 'blind')], default='ALBINISM', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(default='1996-06-06'),
        ),
        migrations.DeleteModel(
            name='Disability',
        ),
        migrations.DeleteModel(
            name='UserDisability',
        ),
    ]
