# Generated by Django 2.2.4 on 2019-08-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20190809_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cause',
            field=models.CharField(blank=True, choices=[('ILLNESS', 'illness'), ('BIRTH', 'birth'), ('ACCIDENT', 'accident')], default='BIRTH', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, default='1996-06-06', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='disability',
            field=models.CharField(blank=True, choices=[('ALBINISM', 'albinism'), ('PHYSICAL', 'physical'), ('MENATL', 'mental'), ('VISUAL', 'visual'), ('HEARING', 'hearing'), ('EPILEPSY', 'epilepsy'), ('BLIND', 'blind')], default='ALBINISM', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, default='email', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='firstname',
            field=models.CharField(blank=True, default='firstname', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lastname',
            field=models.CharField(blank=True, default='lastname', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default='location', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='national_id',
            field=models.CharField(blank=True, default='national id', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nationality',
            field=models.CharField(blank=True, default='nationality', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default='phone number', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, choices=[('MALE', 'male'), ('FEMALE', 'female')], default='sex', max_length=10, null=True),
        ),
    ]
