# Generated by Django 2.2.4 on 2019-08-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_auto_20190810_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cause',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='disability',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nationality',
        ),
        migrations.AddField(
            model_name='profile',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A', 'a'), ('B', 'b'), ('AB', 'ab'), ('O', 'o')], default='ALBINISM', max_length=15, null=True),
        ),
    ]
