# Generated by Django 2.2.4 on 2019-08-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_auto_20190816_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A', 'a'), ('B', 'b'), ('AB', 'ab'), ('O', 'o')], default='blood type', max_length=15, null=True),
        ),
    ]
